In [1]:
import pandas as pd

In [2]:
races=pd.read_csv('../Data/races.csv')
drivers=pd.read_csv('../Data/drivers.csv')
results=pd.read_csv('../Data/results.csv')
qualifying=pd.read_csv('../Data/qualifying.csv')
pit_stops=pd.read_csv('../Data/pit_stops.csv')
lap_time=pd.read_csv('../Data/lap_times.csv')
constructors=pd.read_csv('../Data/constructors.csv')

In [3]:
dataset={
    "races":races,
    "drivers":drivers,
    "results":results,
    "qualifying":qualifying,
    "pit_stops":pit_stops,
    "lap_time":lap_time,
    "constructors":constructors
}

In [4]:
races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

In [5]:
drivers

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

In [6]:
results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,\N,\N,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,\N,\N,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,\N,R,18,0.0,30,\N,\N,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,\N,R,19,0.0,26,\N,\N,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,\N,R,20,0.0,0,\N,\N,\N,0,\N,\N,4

In [7]:
qualifying

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236
...,...,...,...,...,...,...,...,...,...
10489,10547,1144,848,3,23,16,1:23.821,\N,\N
10490,10548,1144,855,15,24,17,1:23.880,\N,\N
10491,10549,1144,1,131,44,18,1:23.887,\N,\N
10492,10550,1144,861,3,43,19,1:23.912,\N,\N
10493,10551,1144,862,214,61,20,1:24.105,\N,\N

In [8]:
pit_stops

       raceId  driverId  stop  lap      time duration  milliseconds
0         841       153     1    1  17:05:23   26.898         26898
1         841        30     1    1  17:05:52   25.021         25021
2         841        17     1   11  17:20:48   23.426         23426
3         841         4     1   12  17:22:34   23.251         23251
4         841        13     1   13  17:24:10   23.842         23842
...       ...       ...   ...  ...       ...      ...           ...
11366    1144       840     2   32  17:52:48   22.053         22053
11367    1144         1     1   34  17:55:17   21.694         21694
11368    1144         4     2   37  18:00:10   22.437         22437
11369    1144       855     2   39  18:03:21   28.765         28765
11370    1144       825     4   55  18:28:06   22.090         22090

[11371 rows x 7 columns]

In [9]:
lap_time

        raceId  driverId  lap  position      time  milliseconds
0          841        20    1         1  1:38.109         98109
1          841        20    2         1  1:33.006         93006
2          841        20    3         1  1:32.713         92713
3          841        20    4         1  1:32.803         92803
4          841        20    5         1  1:32.342         92342
...        ...       ...  ...       ...       ...           ...
589076    1144       857   54        10  1:27.731         87731
589077    1144       857   55        10  1:27.781         87781
589078    1144       857   56        10  1:27.816         87816
589079    1144       857   57        10  1:28.554         88554
589080    1144       857   58        10  1:28.010         88010

[589081 rows x 6 columns]

In [10]:
constructors

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
211,215,rb,RB F1 Team,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team

In [11]:
for i,df in dataset.items():
    print(i)
    print(df.isnull().sum())

races
raceId         0
year           0
round          0
circuitId      0
name           0
date           0
time           0
url            0
fp1_date       0
fp1_time       0
fp2_date       0
fp2_time       0
fp3_date       0
fp3_time       0
quali_date     0
quali_time     0
sprint_date    0
sprint_time    0
dtype: int64
drivers
driverId       0
driverRef      0
number         0
code           0
forename       0
surname        0
dob            0
nationality    0
url            0
dtype: int64
results
resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64
qualifying
qualifyId         0
raceId            0
driverId          0
constructorId     0
number            0
position          0
q1                0
q2               22
q3               46
dtype: int64
pit_stops
raceId          0
driverId        0
stop            0
lap             0
time            0
duration        0
milliseconds    0
dtype: int64
lap_time
raceId          0
driverId        0
lap             0
position        0
time            0
milliseconds    0
dtype: int64
constructors
constructorId     0
constructorRef    0
name              0
nationality       0
url               0
dtype: int64

In [12]:
master=results.merge(
    races[['raceId','year','name']],
    on='raceId'
)
master=master.merge(
    drivers[['driverId','forename','surname']],
    on='driverId'
)
master=master.merge(
    constructors[['constructorId','name']],
    on='constructorId'
)

In [13]:
master.rename(
    columns={
        'name_x':'race_name',
        'name_y':'constructor_name'
    },
    inplace=True
)

In [14]:
master['driver_name']=(
    master['forename']
    +" "
    +master['surname']
)

In [15]:
master

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,rank,fastestLapTime,fastestLapSpeed,statusId,year,race_name,forename,surname,constructor_name,driver_name
0,1,18,1,1,22,1,1,1,1,10.0,...,2,1:27.452,218.300,1,2008,Australian Grand Prix,Lewis,Hamilton,McLaren,Lewis Hamilton
1,2,18,2,2,3,5,2,2,2,8.0,...,3,1:27.739,217.586,1,2008,Australian Grand Prix,Nick,Heidfeld,BMW Sauber,Nick Heidfeld
2,3,18,3,3,7,7,3,3,3,6.0,...,5,1:28.090,216.719,1,2008,Australian Grand Prix,Nico,Rosberg,Williams,Nico Rosberg
3,4,18,4,4,5,11,4,4,4,5.0,...,7,1:28.603,215.464,1,2008,Australian Grand Prix,Fernando,Alonso,Renault,Fernando Alonso
4,5,18,5,1,23,3,5,5,5,4.0,...,1,1:27.418,218.385,1,2008,Australian Grand Prix,Heikki,Kovalainen,McLaren,Heikki Kovalainen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,...,1,1:25.637,222.002,11,2024,Abu Dhabi Grand Prix,Kevin,Magnussen,Haas F1 Team,Kevin Magnussen
26755,26761,1144,859,215,30,12,17,17,17,0.0,...,12,1:28.751,214.212,5,2024,Abu Dhabi Grand Prix,Liam,Lawson,RB F1 Team,Liam Lawson
26756,26762,1144,822,15,77,9,\N,R,18,0.0,...,19,1:29.482,212.462,130,2024,Abu Dhabi Grand Prix,Valtteri,Bottas,Sauber,Valtteri Bottas
26757,26763,1144,861,3,43,20,\N,R,19,0.0,...,17,1:29.411,212.631,5,2024,Abu Dhabi Grand Prix,Franco,Colapinto,Williams,Franco Colapinto
26758,26764,1144,815,9,11,10,\N,R,20,0.0,...,0,\N,\N,4,2024,Abu Dhabi Grand Prix,Sergio,Pérez,Red Bull,Sergio Pérez

In [16]:
master.to_csv(
    '../Data/master.csv',
    index=False,
)